In [ ]:
#Q.1
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Union of two sets
union_set = set1.union(set2)
print("Union of set1 and set2:", union_set)

# Intersection of two sets
intersection_set = set1.intersection(set2)
print("Intersection of set1 and set2:", intersection_set)

# Difference between set1 and set2
difference_set = set1.difference(set2)
print("Difference between set1 and set2:", difference_set)

# Symmetric difference between set1 and set2
symmetric_difference_set = set1.symmetric_difference(set2)
print("Symmetric difference between set1 and set2:", symmetric_difference_set)


In [ ]:
#Q.2
dict1 = {'b': 2, 'a': 1, 'd': 4, 'c': 3}
sorted_key_asc = dict(sorted(dict1.items()))
print("Sorted by key (ascending):", sorted_key_asc)
sorted_key_desc = dict(sorted(dict1.items(), reverse=True))
print("Sorted by key (descending):", sorted_key_desc)
sorted_value_asc = dict(sorted(dict1.items(), key=lambda item: item[1]))
print("Sorted by value (ascending):", sorted_value_asc)
sorted_value_desc = dict(sorted(dict1.items(), key=lambda item: item[1], reverse=True))
print("Sorted by value (descending):", sorted_value_desc)


In [ ]:
#Write a program to count the numbers of characters in the given string and store them
#in a dictionary data structure in python
# Example string
str1 = "Hello, world!"

# Count characters in the string and store them in a dictionary
char_counts = {char: str1.count(char) for char in str1}

# Print the character counts
for char, count in char_counts.items():
    print(f"{char}: {count}")


In [ ]:
#Q4
def generate_squared_dictionary(n):
    squared_dict = {}
    for i in range(1, n+1):
        squared_dict[i] = i * i
    return squared_dict

# Example value of n
n = 5

# Generate the squared dictionary
squared_dictionary = generate_squared_dictionary(n)

# Print the squared dictionary
print(squared_dictionary)


In [ ]:
#Q.5
def find_pair_indices(numbers, target):
    num_dict = {}
    for i, num in enumerate(numbers):
        complement = target - num
        if complement in num_dict:
            return [num_dict[complement], i]
        num_dict[num] = i
    return []

# Example array of numbers and target
numbers = [2, 7, 11, 15]
target = 9

# Find the pair of elements
pair_indices = find_pair_indices(numbers, target)

# Print the pair indices
if pair_indices:
    print("Pair indices:", pair_indices[0], pair_indices[1])
else:
    print("No pair found with the given target.")


In [ ]:
#Q.6
# Accepting input from the user
name = input("Enter student name: ")
age = int(input("Enter student age: "))
marks = float(input("Enter student marks: "))

# Checking eligibility criteria
if age >= 17 and age <= 21 and marks >= 80:
    print(f"{name} is eligible for the student loan.")
else:
    print(f"{name} is not eligible for the student loan.")


In [ ]:
#Q7
class Library:
    def __init__(self, acc_number, publisher, title, author):
        self.acc_number = acc_number
        self.publisher = publisher
        self.title = title
        self.author = author

    def read(self):
        print("Acc-Number:", self.acc_number)
        print("Title:", self.title)
        print("Author:", self.author)
        print("Publisher:", self.publisher)

    def compute(self, days_late):
        fine = days_late * 5
        print("Fine charged:", fine, "Rupees")

    def display(self):
        print("Acc-Number:", self.acc_number)
        print("Title:", self.title)
        print("Author:", self.author)
        print("Publisher:", self.publisher)


# Create an instance of the Library class
book = Library("123456", "Publisher X", "Book Title", "Author Name")

# Call the read method to display the book details
book.read()

# Call the compute method to calculate and display the fine
book.compute(7)

# Call the display method to show the book details again
book.display()


In [ ]:
#Q.8
class Investment:
    def __init__(self, principal, interest):
        self.principal = principal
        self.interest = interest

    def value_after(self, years):
        value = self.principal * (1 + self.interest) ** years
        return value


# Create an instance of the Investment class
investment = Investment(1000, 0.05)

# Calculate the value after 3 years
value_after_3_years = investment.value_after(3)
print("Value after 3 years:", value_after_3_years)

# Calculate the value after 5 years
value_after_5_years = investment.value_after(5)
print("Value after 5 years:", value_after_5_years)


In [ ]:
#Q9
class StringProcessor:
    def __init__(self):
        self.input_str = ""

    def getString(self):
        self.input_str = input("Enter a string: ")

    def printString(self):
        print("Input string:", self.input_str.upper())


# Create an instance of the StringProcessor class
processor = StringProcessor()

# Call the getString method to get a string from console input
processor.getString()

# Call the printString method to print the input string in uppercase
processor.printString()


In [ ]:
#Q.10
import math

class Circle:
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * self.radius**2

    def perimeter(self):
        return 2 * math.pi * self.radius


# Create an instance of the Circle class with a radius of 5
circle = Circle(5)

# Calculate and print the area of the circle
circle_area = circle.area()
print("Area:", circle_area)

# Calculate and print the perimeter of the circle
circle_perimeter = circle.perimeter()
print("Perimeter:", circle_perimeter)


In [ ]:
#Q12. Write a Python program to check the validity of a password (input from users).
#Validation :

import re

def validate_password(password):
    if len(password) < 6 or len(password) > 16:
        return False

    if not re.search(r"[a-z]", password):
        return False

    if not re.search(r"[A-Z]", password):
        return False

    if not re.search(r"\d", password):
        return False

    if not re.search(r"[$#@]", password):
        return False

    return True


# Prompt the user to enter a password
password = input("Enter a password: ")

# Validate the password
valid = validate_password(password)

# Display the result
if valid:
    print("Password is valid.")
else:
    print("Password is not valid.")


In [1]:
#Q11
class Shape:
    def __init__(self):
        self.area = 0

    def calculate_area(self):
        print("Area of the shape:", self.area)


class Square(Shape):
    def __init__(self, length):
        super().__init__()
        self.length = length

    def calculate_area(self):
        self.area = self.length**2
        print("Area of the square:", self.area)


# Create an instance of the Shape class
shape = Shape()
shape.calculate_area()  # Output: Area of the shape: 0

# Create an instance of the Square class with length 5
square = Square(5)
square.calculate_area()  # Output: Area of the square: 25


Area of the shape: 0
Area of the square: 25


In [2]:
#Q.13

import re

def validate_email(email):
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    return re.match(pattern, email) is not None

# Prompt the user to enter an email ID
email_id = input("Enter an email ID: ")

# Validate the email ID
valid = validate_email(email_id)

# Display the result
if valid:
    print("Email ID is valid.")
else:
    print("Email ID is not valid.")


Enter an email ID: 
Email ID is not valid.


In [3]:
#Q14
import re

def validate_mobile_number(number):
    pattern = r'^[7-9]\d{9}$'
    return re.match(pattern, number) is not None

# Prompt the user to enter a mobile number
mobile_number = input("Enter a 10-digit mobile number: ")

# Validate the mobile number
valid = validate_mobile_number(mobile_number)

# Display the result
if valid:
    print("Valid mobile number.")
else:
    print("Invalid mobile number.")


Enter a 10-digit mobile number: 
Invalid mobile number.


In [4]:
#Q15
# Predefined list of employees
employees = ['Alice', 'Bob', 'Charlie', 'Dave']

# Prompt the user to enter an employee name
employee_name = input("Enter the name of an employee: ")

# Check if the entered employee name is in the list
if employee_name not in employees:
    raise ValueError("Employee not found!")

# If the employee name is found, continue with the program logic
# ...





Enter the name of an employee: 


ValueError: Employee not found!

In [ ]:
#Q16. Write a programm for synchronization of Threads using RLOCK. Accept the two
#numbers from user and calculate factorial of both Numbers simultaneously
import threading

def calculate_factorial(number, lock):
    result = 1
    for i in range(1, number + 1):
        lock.acquire()
        result *= i
        lock.release()
    print(f"Factorial of {number} is {result}")

# Accept two numbers from the user
number1 = int(input("Enter the first number: "))
number2 = int(input("Enter the second number: "))

# Create an RLock object
lock = threading.RLock()

# Create two threads for calculating factorial of each number
thread1 = threading.Thread(target=calculate_factorial, args=(number1, lock))
thread2 = threading.Thread(target=calculate_factorial, args=(number2, lock))

# Start both threads
thread1.start()
thread2.start()

# Wait for both threads to finish
thread1.join()
thread2.join()



In [6]:
#Q17. Write a multithreading program where one thread prints square of a number and
#another thread prints factorial of a number. Also display the total time taken for the
#execution

import threading
import time
import math

def calculate_square(number):
    square = number ** 2
    print(f"Square of {number}: {square}")

def calculate_factorial(number):
    factorial = math.factorial(number)
    print(f"Factorial of {number}: {factorial}")

# Accept the number from the user
number = int(input("Enter a number: "))

# Create a timer to measure execution time
start_time = time.time()

# Create two threads for calculating square and factorial
thread1 = threading.Thread(target=calculate_square, args=(number,))
thread2 = threading.Thread(target=calculate_factorial, args=(number,))

# Start both threads
thread1.start()
thread2.start()

# Wait for both threads to finish
thread1.join()
thread2.join()

# Calculate the total execution time
total_time = time.time() - start_time
print(f"Total time taken: {total_time} seconds")


Enter a number: 14
Square of 14: 196
Factorial of 14: 87178291200
Total time taken: 0.002960205078125 seconds


In [7]:
#Q18. Write a python program to check the given number is prime or not. Handle Suitable
#Exception
def is_prime(number):
    if number < 2:
        return False

    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            return False

    return True

try:
    number = int(input("Enter a number: "))
    if is_prime(number):
        print(f"{number} is a prime number.")
    else:
        print(f"{number} is not a prime number.")
except ValueError:
    print("Invalid input. Please enter a valid integer.")
except Exception as e:
    print("An error occurred:", e)


Enter a number: 5
5 is a prime number.


In [8]:
#Q19. Develop a program to Print the number of line,words,and characters present in the
#given file. Accept the file name from user. Handle necessary exceptions
def count_file_stats(file_name):
    try:
        with open(file_name, 'r') as file:
            lines = 0
            words = 0
            characters = 0

            for line in file:
                lines += 1
                words += len(line.split())
                characters += len(line)

            print(f"Number of lines: {lines}")
            print(f"Number of words: {words}")
            print(f"Number of characters: {characters}")

    except FileNotFoundError:
        print(f"File '{file_name}' not found.")
    except PermissionError:
        print(f"Permission denied to open file '{file_name}'.")
    except Exception as e:
        print("An error occurred:", e)


# Accept the file name from the user
file_name = input("Enter the file name: ")

# Call the function to count file statistics
count_file_stats(file_name)


Enter the file name: 
File '' not found.


In [9]:
#Q20. Python Program to Append the Contents of One File to Another File
def append_file(source_file, destination_file):
    try:
        with open(source_file, 'r') as source, open(destination_file, 'a') as destination:
            contents = source.read()
            destination.write(contents)

        print("File contents appended successfully.")
    except FileNotFoundError:
        print("One or both files not found.")
    except PermissionError:
        print("Permission denied to open file(s).")
    except Exception as e:
        print("An error occurred:", e)


# Accept the file names from the user
source_file = input("Enter the source file name: ")
destination_file = input("Enter the destination file name: ")

# Call the function to append file contents
append_file(source_file, destination_file)


Enter the source file name: 
Enter the destination file name: 
One or both files not found.


In [10]:
#Q21. Develop a program to remove the comment character from all the lines in a given file.
#Accept file name from user
def remove_comments(file_name):
    try:
        with open(file_name, 'r') as file:
            lines = file.readlines()

        # Remove comment character from each line
        lines = [line.split('#', 1)[0] for line in lines]

        with open(file_name, 'w') as file:
            file.writelines(lines)

        print("Comments removed successfully.")
    except FileNotFoundError:
        print(f"File '{file_name}' not found.")
    except PermissionError:
        print(f"Permission denied to open file '{file_name}'.")
    except Exception as e:
        print("An error occurred:", e)


# Accept the file name from the user
file_name = input("Enter the file name: ")

# Call the function to remove comments from the file
remove_comments(file_name)


Enter the file name: 
File '' not found.


In [11]:
#Q.22Write a python program to read "employee.txt" file and display the alternate
#employee records.
def display_alternate_records(file_name):
    try:
        with open(file_name, 'r') as file:
            lines = file.readlines()

        # Display alternate employee records
        for i in range(len(lines)):
            if i % 2 == 0:
                print(lines[i])

        print("Alternate employee records displayed successfully.")
    except FileNotFoundError:
        print(f"File '{file_name}' not found.")
    except PermissionError:
        print(f"Permission denied to open file '{file_name}'.")
    except Exception as e:
        print("An error occurred:", e)


# Provide the file name
file_name = "employee.txt"

# Call the function to display alternate employee records
display_alternate_records(file_name)


Name: priya

Alternate employee records displayed successfully.


In [12]:
#Q23. Write a Python program to combine each line from first file with the corresponding
#line in second file.
def combine_files(file1, file2, output_file):
    try:
        with open(file1, 'r') as file1, open(file2, 'r') as file2, open(output_file, 'w') as output:
            lines1 = file1.readlines()
            lines2 = file2.readlines()

            # Combine lines from both files and write to the output file
            for line1, line2 in zip(lines1, lines2):
                combined_line = line1.strip() + " " + line2.strip() + "\n"
                output.write(combined_line)

        print("Files combined successfully.")
    except FileNotFoundError:
        print("One or more files not found.")
    except PermissionError:
        print("Permission denied to open file(s).")
    except Exception as e:
        print("An error occurred:", e)


# Provide the file names
file1 = "file1.txt"
file2 = "file2.txt"
output_file = "combined.txt"

# Call the function to combine the files
combine_files(file1, file2, output_file)



One or more files not found.


In [13]:
"""Write a Python program to perform following operation on MongoDB database
i) Create collection "Book" with fields
Book-name, Book-code, Book-Author, Book-Price,Book-publication-year
ii) Insert 5 documents
iii)Find the books whose price between 500-800.
iv) Update price of book "Python programming" as 1000""" 

from pymongo import MongoClient

# Connect to the MongoDB server
client = MongoClient('mongodb://localhost:27017/')

# Access the "Book" database
db = client['Book']

# Create the "Book" collection
collection = db['Book']

# Create the collection "Book" with fields
collection.insert_many([
    {
        "Book-name": "Python Programming",
        "Book-code": "PY001",
        "Book-Author": "John Smith",
        "Book-Price": 800,
        "Book-publication-year": 2020
    },
    {
        "Book-name": "Java Programming",
        "Book-code": "JA001",
        "Book-Author": "Emily Johnson",
        "Book-Price": 600,
        "Book-publication-year": 2019
    },
    {
        "Book-name": "JavaScript Basics",
        "Book-code": "JS001",
        "Book-Author": "David Brown",
        "Book-Price": 700,
        "Book-publication-year": 2021
    },
    {
        "Book-name": "C++ Programming",
        "Book-code": "C001",
        "Book-Author": "Sarah Wilson",
        "Book-Price": 400,
        "Book-publication-year": 2018
    },
    {
        "Book-name": "Data Science with Python",
        "Book-code": "DS001",
        "Book-Author": "Michael Lee",
        "Book-Price": 900,
        "Book-publication-year": 2022
    }
])

# Find the books whose price is between 500-800
query = {"Book-Price": {"$gte": 500, "$lte": 800}}
result = collection.find(query)

print("Books with price between 500-800:")
for book in result:
    print(book)

# Update the price of the book "Python Programming" to 1000
update_query = {"Book-name": "Python Programming"}
new_price = {"$set": {"Book-Price": 1000}}
collection.update_one(update_query, new_price)

print("\nBook 'Python Programming' price updated.")

# Close the connection to the MongoDB server
client.close()


Books with price between 500-800:
{'_id': ObjectId('6498f33e31563c56ccfbefdf'), 'Book-name': 'Python Programming', 'Book-code': 'PY001', 'Book-Author': 'John Smith', 'Book-Price': 800, 'Book-publication-year': 2020}
{'_id': ObjectId('6498f33e31563c56ccfbefe0'), 'Book-name': 'Java Programming', 'Book-code': 'JA001', 'Book-Author': 'Emily Johnson', 'Book-Price': 600, 'Book-publication-year': 2019}
{'_id': ObjectId('6498f33e31563c56ccfbefe1'), 'Book-name': 'JavaScript Basics', 'Book-code': 'JS001', 'Book-Author': 'David Brown', 'Book-Price': 700, 'Book-publication-year': 2021}

Book 'Python Programming' price updated.


In [14]:
"""Q25. Write a python program to connect with MongoDB Database. Create collection
“restaurants” (Assume suitable structure). Query the “restaurants” collection to
a. display the fields restaurant_id, name, establishment_year and cuisine for all the
documents in the collection restaurant
b. find the restaurants who achieved a score more than 90.
c. arrange the name of the restaurants in ascending order
d. Update restaurant score for the establishment year 2019"""
from pymongo import MongoClient

# Connect to the MongoDB server
client = MongoClient('mongodb://localhost:27017/')

# Access the "restaurantDB" database
db = client['restaurantDB']

# Create the "restaurants" collection
collection = db['restaurants']

# Query to display restaurant_id, name, establishment_year, and cuisine for all documents
query_a = {}
projection_a = {"restaurant_id": 1, "name": 1, "establishment_year": 1, "cuisine": 1}
restaurants_a = collection.find(query_a, projection_a)

print("Restaurants:")
for restaurant in restaurants_a:
    print(restaurant)

# Query to find restaurants with score > 90
query_b = {"score": {"$gt": 90}}
restaurants_b = collection.find(query_b)

print("\nRestaurants with score > 90:")
for restaurant in restaurants_b:
    print(restaurant)

# Query to arrange restaurant names in ascending order
query_c = {}
projection_c = {"name": 1}
sort_c = [("name", 1)]
restaurants_c = collection.find(query_c, projection_c).sort(sort_c)

print("\nRestaurants sorted by name in ascending order:")
for restaurant in restaurants_c:
    print(restaurant)

# Query to update restaurant score for the establishment year 2019
query_d = {"establishment_year": 2019}
new_score_d = {"$set": {"score": 95}}
collection.update_many(query_d, new_score_d)

print("\nRestaurant scores updated for the establishment year 2019.")

# Close the connection to the MongoDB server
client.close()



Restaurants:

Restaurants with score > 90:

Restaurants sorted by name in ascending order:

Restaurant scores updated for the establishment year 2019.


In [15]:
"""Q26. Write a python program to connect with MongoDB Database. Create collection
“movies” (title, writer, year, actors, director...consider this fields in movies collection).
Query the “movies” collection to
a. get all documents where actors include "Amitabh Bachchan"
b. get all movies released before the year 2000 or after 2010
c. Update some documents by adding some extra fields
d. Delete movie “movie_name”"""

from pymongo import MongoClient

# Connect to the MongoDB server
client = MongoClient('mongodb://localhost:27017/')

# Access the "moviesDB" database
db = client['moviesDB']

# Create the "movies" collection
collection = db['movies']

# Query to get all documents where actors include "Amitabh Bachchan"
query_a = {"actors": "Amitabh Bachchan"}
movies_a = collection.find(query_a)

print("Movies with Amitabh Bachchan:")
for movie in movies_a:
    print(movie)

# Query to get all movies released before the year 2000 or after 2010
query_b = {"$or": [{"year": {"$lt": 2000}}, {"year": {"$gt": 2010}}]}
movies_b = collection.find(query_b)

print("\nMovies released before 2000 or after 2010:")
for movie in movies_b:
    print(movie)

# Query to update some documents by adding extra fields
query_c = {"director": "Christopher Nolan"}
update_c = {"$set": {"genre": "Thriller", "rating": 8.5}}
collection.update_many(query_c, update_c)

print("\nSome documents updated with extra fields.")

# Query to delete a movie by title
query_d = {"title": "Interstellar"}
collection.delete_one(query_d)

print("\nMovie 'Interstellar' deleted.")

# Close the connection to the MongoDB server
client.close()


Movies with Amitabh Bachchan:

Movies released before 2000 or after 2010:

Some documents updated with extra fields.

Movie 'Interstellar' deleted.


In [16]:
"""Q27. Write a python program using numpy to do the following operations
i) create aaray which contains multiples of 2 till 200
ii)Find the number of occurrences of a sequence in a NumPy array
iii)Count the number of elements along a given axis
"""

import numpy as np

# i) Create an array containing multiples of 2 till 200
array_a = np.arange(2, 201, 2)
print("Array of multiples of 2:")
print(array_a)

# ii) Find the number of occurrences of a sequence in a NumPy array
array_b = np.array([1, 2, 3, 2, 1, 2, 3, 4, 5, 6, 2, 3, 4, 2])
sequence = np.array([2, 3])
count = np.count_nonzero(np.correlate(array_b, sequence))
print("\nNumber of occurrences of sequence [2, 3] in array_b:")
print(count)

# iii) Count the number of elements along a given axis
array_c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
count_axis_0 = np.size(array_c, axis=0)
count_axis_1 = np.size(array_c, axis=1)
print("\nNumber of elements along axis 0 in array_c:")
print(count_axis_0)
print("Number of elements along axis 1 in array_c:")
print(count_axis_1)


Array of multiples of 2:
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]

Number of occurrences of sequence [2, 3] in array_b:
13

Number of elements along axis 0 in array_c:
3
Number of elements along axis 1 in array_c:
3


In [17]:
"""Q28. Write a python program using numpy to do the following operations
i) create a 2*2 matrix and find the transpose of it
ii) create two matrices and find the multiplication of matrices."""

import numpy as np

# i) Create a 2x2 matrix and find its transpose
matrix_a = np.array([[1, 2], [3, 4]])
transpose_a = np.transpose(matrix_a)
print("Matrix A:")
print(matrix_a)
print("Transpose of Matrix A:")
print(transpose_a)

# ii) Create two matrices and find their multiplication
matrix_b = np.array([[5, 6], [7, 8]])
matrix_c = np.array([[9, 10], [11, 12]])
multiply_bc = np.dot(matrix_b, matrix_c)
print("\nMatrix B:")
print(matrix_b)
print("Matrix C:")
print(matrix_c)
print("Multiplication of Matrix B and Matrix C:")
print(multiply_bc)


Matrix A:
[[1 2]
 [3 4]]
Transpose of Matrix A:
[[1 3]
 [2 4]]

Matrix B:
[[5 6]
 [7 8]]
Matrix C:
[[ 9 10]
 [11 12]]
Multiplication of Matrix B and Matrix C:
[[111 122]
 [151 166]]


In [21]:
"""Q29. Write a python program to do the following operations on Numpy Array
i) Find the k smallest values of a NumPy
ii) Compute the nth percentile of the NumPy array
iii) Calculate the sum of all columns in a 2D NumPy array
iv)Calculate average values of two given NumPy arrays
"""
import numpy as np

# i) Find the k smallest values of a NumPy array
array_a = np.array([9, 2, 5, 1, 7, 4, 8, 3, 6])
k=3
k_smallest_values = np.sort(array_a)[:k]
print("K smallest values of array_a:")
print(k_smallest_values)

# ii) Compute the nth percentile of the NumPy array
array_b = np.array([12, 18, 22, 28, 36, 42, 56, 64, 72, 80])
n = 75
percentile_n = np.percentile(array_b, n)
print("\n{}th percentile of array_b:".format(n))
print(percentile_n)

# iii) Calculate the sum of all columns in a 2D NumPy array
array_c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum_columns = np.sum(array_c, axis=0)
print("\nSum of all columns in array_c:")
print(sum_columns)

# iv) Calculate average values of two given NumPy arrays
array_d = np.array([10, 20, 30])
array_e = np.array([5, 15, 25])
average_values = (array_d + array_e) / 2
print("\nAverage values of array_d and array_e:")
print(average_values)




K smallest values of array_a:
[1 2 3]

75th percentile of array_b:
62.0

Sum of all columns in array_c:
[12 15 18]

Average values of array_d and array_e:
[ 7.5 17.5 27.5]


In [22]:
"""Q30. Write a python program to do the following operations on Numpy Array
i )Create a 5X2 integer array from a range between 100 to 200 such that the difference
between each element is 10
ii) Return array of odd rows and even columns from below numpy array
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])"""

import numpy as np

# i) Create a 5x2 integer array from a range between 100 to 200 with a difference of 10
array_a = np.arange(100, 200, 10).reshape(5, 2)
print("Array A:")
print(array_a)

# ii) Return array of odd rows and even columns from the given numpy array
sampleArray = np.array([[3, 6, 9, 12], [15, 18, 21, 24], [27, 30, 33, 36], [39, 42, 45, 48], [51, 54, 57, 60]])
odd_rows_even_cols = sampleArray[::2, 1::2]
print("\nArray of odd rows and even columns:")
print(odd_rows_even_cols)


Array A:
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]

Array of odd rows and even columns:
[[ 6 12]
 [30 36]
 [54 60]]


In [23]:
"""Q31. Write a Python program to get the number of days of a given month and year"""

import calendar

def get_num_days(month, year):
    # Use the monthrange() function from the calendar module to get the number of days
    num_days = calendar.monthrange(year, month)[1]
    return num_days

# Test the function
month = int(input("Enter the month (1-12): "))
year = int(input("Enter the year: "))

num_days = get_num_days(month, year)
print("Number of days in {}-{}: {}".format(month, year, num_days))


Enter the month (1-12): 4
Enter the year: 2002
Number of days in 4-2002: 30


In [24]:
"""Q32. Write a Python program to convert two date difference in days, hours, minutes,
seconds"""
from datetime import datetime

start_date_str = input("Enter the start date (YYYY-MM-DD HH:MM:SS): ")
end_date_str = input("Enter the end date (YYYY-MM-DD HH:MM:SS): ")

start_date = datetime.strptime(start_date_str, "%Y-%m-%d %H:%M:%S")
end_date = datetime.strptime(end_date_str, "%Y-%m-%d %H:%M:%S")

time_diff = end_date - start_date

days = time_diff.days
hours, remainder = divmod(time_diff.seconds, 3600)
minutes, seconds = divmod(remainder, 60)

print("Difference: {} days, {} hours, {} minutes, {} seconds".format(days, hours, minutes, seconds))


Enter the start date (YYYY-MM-DD HH:MM:SS): 2002-04-02 04:02:22
Enter the end date (YYYY-MM-DD HH:MM:SS): 2023-06-26 04:02:22
Difference: 7755 days, 0 hours, 0 minutes, 0 seconds


In [27]:
"""Q33. Write a Python program to do the following operations:
Data set: Iris.csv
a) Loading data from CSV file
b) Compute the basic statistics of given data - shape, no. of columns, mean
c) Visualize data using Scatter plot
"""
import pandas as pd
import matplotlib.pyplot as plt

# a) Loading data from CSV file
data = pd.read_csv('iris.csv')

# b) Compute the basic statistics of given data
shape = data.shape
num_columns = len(data.columns)
mean = data.mean()

print("Shape of data:", shape)
print("Number of columns:", num_columns)
print("Mean values:")
print(mean)

# c) Visualize data using Scatter plot
plt.scatter(data['SepalLengthCm'], data['SepalWidthCm'])
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.title('Scatter plot of Sepal Length vs Sepal Width')
plt.show()


Shape of data: (150, 5)
Number of columns: 5
Mean values:
sepal.length    5.843333
sepal.width     3.057333
petal.length    3.758000
petal.width     1.199333
dtype: float64


C:\Users\admin\AppData\Local\Temp\ipykernel_12460\365006440.py:16: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean = data.mean()


KeyError: 'SepalLengthCm'

In [28]:
"""Q34. Write a python code for handling missing data using fillna(),dropna() method on
Iris.csv file[fill the data using mean/median/mode value]
"""
import pandas as pd

# Load the Iris dataset
data = pd.read_csv('iris.csv')

# Display the number of missing values in each column
print("Number of missing values before handling:")
print(data.isnull().sum())

# Fill missing values with mean
data_filled_mean = data.fillna(data.mean())

# Fill missing values with median
data_filled_median = data.fillna(data.median())

# Fill missing values with mode
data_filled_mode = data.fillna(data.mode().iloc[0])

# Drop rows with missing values
data_dropped = data.dropna()

# Display the number of missing values in each column after handling
print("\nNumber of missing values after handling:")
print(data_filled_mean.isnull().sum())

# Display the filled datasets
print("\nData with missing values filled using mean:")
print(data_filled_mean.head())

print("\nData with missing values filled using median:")
print(data_filled_median.head())

print("\nData with missing values filled using mode:")
print(data_filled_mode.head())

# Display the dropped dataset
print("\nData with missing values dropped:")
print(data_dropped.head())


Number of missing values before handling:
sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

Number of missing values after handling:
sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

Data with missing values filled using mean:
   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

Data with missing values filled using median:
   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3

C:\Users\admin\AppData\Local\Temp\ipykernel_12460\1280770191.py:14: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data_filled_mean = data.fillna(data.mean())
C:\Users\admin\AppData\Local\Temp\ipykernel_12460\1280770191.py:17: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data_filled_median = data.fillna(data.median())


In [29]:
"""Q35. Create a DataFrame from a dictionary with the following data:
'Name': ['John', 'Emma', 'Peter', 'Olivia']
'Age': [25, 30, 28, 35]
'City': ['New York', 'London', 'Paris', 'Sydney']
i. Display the created DataFrame.
ii. Access the 'Name' column of the DataFrame.
iii. Access the second row of the DataFrame.
iv. Add a new column 'Gender' with values ['M', 'F', 'M', 'F'] to the DataFrame.
v. Update the 'City' value of the third row to 'Tokyo'.\
"""
import pandas as pd

# Create the dictionary
data = {
    'Name': ['John', 'Emma', 'Peter', 'Olivia'],
    'Age': [25, 30, 28, 35],
    'City': ['New York', 'London', 'Paris', 'Sydney']
}

# Create the DataFrame
df = pd.DataFrame(data)

# i. Display the created DataFrame
print("Created DataFrame:")
print(df)

# ii. Access the 'Name' column of the DataFrame
name_column = df['Name']
print("\n'Name' column of the DataFrame:")
print(name_column)

# iii. Access the second row of the DataFrame
second_row = df.iloc[1]
print("\nSecond row of the DataFrame:")
print(second_row)

# iv. Add a new column 'Gender' with values ['M', 'F', 'M', 'F'] to the DataFrame
df['Gender'] = ['M', 'F', 'M', 'F']
print("\nDataFrame with the 'Gender' column:")
print(df)

# v. Update the 'City' value of the third row to 'Tokyo'
df.at[2, 'City'] = 'Tokyo'
print("\nDataFrame with updated 'City' value:")
print(df)




Created DataFrame:
     Name  Age      City
0    John   25  New York
1    Emma   30    London
2   Peter   28     Paris
3  Olivia   35    Sydney

'Name' column of the DataFrame:
0      John
1      Emma
2     Peter
3    Olivia
Name: Name, dtype: object

Second row of the DataFrame:
Name      Emma
Age         30
City    London
Name: 1, dtype: object

DataFrame with the 'Gender' column:
     Name  Age      City Gender
0    John   25  New York      M
1    Emma   30    London      F
2   Peter   28     Paris      M
3  Olivia   35    Sydney      F

DataFrame with updated 'City' value:
     Name  Age      City Gender
0    John   25  New York      M
1    Emma   30    London      F
2   Peter   28     Tokyo      M
3  Olivia   35    Sydney      F


In [30]:
"""Q36. Use Bollywood.csv file to answer this questions:
a) How many records are present in the dataset? Print the metadata information of the
dataset.
b)How many movies got released in each genre? Which genre had highest number of
releases? Sort number of releases in each genre in descending order.
c) Which month of the year, maximum, number movie releases are seen?(Note:
Extract a new column called month from releaseDate column)
"""

import pandas as pd

# a) How many records are present in the dataset? Print the metadata information of the dataset.
df = pd.read_csv('Bollywood.csv')
num_records = len(df)
print("Number of records:", num_records)
print("\nMetadata information:")
print(df.info())

# b) How many movies got released in each genre? Which genre had the highest number of releases? Sort number of releases in each genre in descending order.
genre_counts = df['Genre'].value_counts()
print("\nNumber of releases in each genre:")
print(genre_counts)
max_genre = genre_counts.idxmax()
print("\nGenre with the highest number of releases:", max_genre)

# c) Which month of the year had the maximum number of movie releases? (Note: Extract a new column called 'month' from the 'releaseDate' column)
df['month'] = pd.to_datetime(df['releaseDate']).dt.month
month_counts = df['month'].value_counts()
max_month = month_counts.idxmax()
print("\nMonth with the maximum number of movie releases:", max_month)


FileNotFoundError: [Errno 2] No such file or directory: 'Bollywood.csv'

In [ ]:
"""Q38. Use company_sales_data.csv file to answer this questions:
a. Read Total profit of all months and show it using a line plot
b. Get total profit of all months and show line plot with the following Style properties:
i. Line Style dotted and Line-color should be red
ii. Show legend at the lower right location.
iii. X label name = Month Number
iv. Y label name = Sold units number
"""

import pandas as pd
import matplotlib.pyplot as plt

# a) Read Total profit of all months and show it using a line plot
df = pd.read_csv('company_sales_data.csv')
months = df['month_number']
profits = df['total_profit']
plt.plot(months, profits)
plt.xlabel('Month Number')
plt.ylabel('Total Profit')
plt.title('Total Profit of All Months')
plt.show()

# b) Get total profit of all months and show line plot with the specified style properties
plt.plot(months, profits, linestyle='dotted', color='red')
plt.xlabel('Month Number')
plt.ylabel('Total Profit')
plt.title('Total Profit of All Months')
plt.legend(['Total Profit'], loc='lower right')
plt.show()


In [ ]:
"""Q39. Use company_sales_data.csv file to answer this questions:
a. Read all product sales data and show it using a multiline plot
b. Read face cream and facewash product sales data and show it using the bar chart
c. Calculate total sale data for last year for each product and show it using a Pie chart
"""
import pandas as pd
import matplotlib.pyplot as plt

# a) Read all product sales data and show it using a multiline plot
df = pd.read_csv('company_sales_data.csv')
months = df['month_number']
face_cream_sales = df['facecream']
face_wash_sales = df['facewash']
toothpaste_sales = df['toothpaste']
bathing_soap_sales = df['bathingsoap']
shampoo_sales = df['shampoo']
moisturizer_sales = df['moisturizer']

plt.plot(months, face_cream_sales, label='Face Cream')
plt.plot(months, face_wash_sales, label='Face Wash')
plt.plot(months, toothpaste_sales, label='Toothpaste')
plt.plot(months, bathing_soap_sales, label='Bathing Soap')
plt.plot(months, shampoo_sales, label='Shampoo')
plt.plot(months, moisturizer_sales, label='Moisturizer')

plt.xlabel('Month Number')
plt.ylabel('Sales Units')
plt.title('Product Sales Data')
plt.legend()
plt.show()

# b) Read face cream and facewash product sales data and show it using a bar chart
plt.bar(months, face_cream_sales, label='Face Cream')
plt.bar(months, face_wash_sales, label='Face Wash')

plt.xlabel('Month Number')
plt.ylabel('Sales Units')
plt.title('Face Cream and Face Wash Sales Data')
plt.legend()
plt.show()

# c) Calculate total sale data for last year for each product and show it using a Pie chart
last_year_sales = df.loc[df['year'] == df['year'].max()]
last_year_sales = last_year_sales.drop(columns=['month_number', 'year', 'total_units', 'total_profit'])
product_totals = last_year_sales.sum()

product_names = product_totals.index
product_sales = product_totals.values

plt.pie(product_sales, labels=product_names, autopct='%1.1f%%')
plt.title('Total Sales for Last Year')
plt.show()


In [ ]:
"""Q40. Create a NumPy array of shape (5, 5) with random integers ranging from 1 to 100.
Perform the following operations:
i. Find the sum of all elements in the array.
ii. Calculate the mean of each row in the array.
iii. Compute the standard deviation of each column in the array.
"""

import numpy as np

# Create a NumPy array of shape (5, 5) with random integers ranging from 1 to 100
arr = np.random.randint(1, 101, size=(5, 5))

# i. Find the sum of all elements in the array
sum_of_elements = np.sum(arr)
print("Sum of all elements:", sum_of_elements)

# ii. Calculate the mean of each row in the array
mean_of_rows = np.mean(arr, axis=1)
print("Mean of each row:", mean_of_rows)

# iii. Compute the standard deviation of each column in the array
std_dev_of_columns = np.std(arr, axis=0)
print("Standard deviation of each column:", std_dev_of_columns)
